# Kernel module Makefile
# This is invoked by the root Makefile to build the kernel module

obj-m := message_slot.o

# Tell kbuild to look for headers in the include directory
ccflags-y := -I$(src)/../include
